#! /bin/bash
echo BUILD
rm Bin/FacOversampler
g++ -c BandLimit.cpp
g++ -std=c++11 -c FacOversampler.cpp
g++ -o FacOversampler BandLimit.o FacOversampler.o
mv FacOversampler Bin/FacOversampler
./Bin/FacOversampler $1
